# Site settings
title: Ronel Zapata
SEOTitle: Ronel Zapata
header-img: img/main-banner.png
email: ronelzb@gmail.com
# description: 
keyword: "RZ, Ronel Zapata, ronelzb, .NET, Java, Python, SQL Server, Full-Stack developer, Software engineer"
url: "https://ronelzb.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/ronelzb/ronelzb.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Dreams don't work unless you take action. The surest way to make your dreams come true is to live them."
#sidebar-avatar: #/img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
github_username:    ronelzb
facebook_username:  ronelzb
twitter_username:   ronelzb
linkedin_username: ronel-josé-zapata-beltrán-b86b2733

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                              # use Github Flavored Markdown !important

# Google Analytics
#ga_track_id: 
#ga_domain: auto                          # The default is auto, if you don’t have your own domain name, you need to keep it at auto
ga_meas_id: 'G-84XP2BGW7K'

# Featured Tags
featured-tags: false                      # Whether to use the homepage tag
featured-condition-size: 1                # Only if the number of the same label is greater than this number, it will appear on the homepage

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
# friends: [
#     {
#         title: "WY",
#         href: "http://zhengwuyang.com"
#     },{
#         title: "简书·BY",
#         href: "http://www.jianshu.com/u/e71990ada2fd"
#     },{
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]